2023-03-09 10:19:55,278 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:20:00,059 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:20:04,575 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:20:08,672 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:21:38,402 ERROR: Exception on / [POST] [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1186, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py", line 303, in homepage
    website.users.append(current_user)
    ^^^^^^^^^^^^^
AttributeError: 'Website' object has no attribute 'users'
2023-03-09 10:26:22,146 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:26:23,947 ERROR: Exception on / [POST] [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1186, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py", line 303, in homepage
    website.users.append(current_user)
    ^^^^^^^^^^^^^
AttributeError: 'Website' object has no attribute 'users'
2023-03-09 10:26:37,660 ERROR: Exception on / [POST] [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1186, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py", line 303, in homepage
    website.users.append(current_user)
    ^^^^^^^^^^^^^
AttributeError: 'Website' object has no attribute 'users'
2023-03-09 10:28:00,428 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:28:02,480 ERROR: Exception on / [POST] [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/venv/lib/python3.11/site-packages/flask_limiter/extension.py", line 1186, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py", line 303, in homepage
    website.users.append(current_user)
    ^^^^^^^^^^^^^
AttributeError: 'Website' object has no attribute 'users'
2023-03-09 10:29:49,895 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:40:37,671 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:43:53,386 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 10:50:43,446 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 13:54:50,728 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 14:12:43,607 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 14:12:57,623 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 14:13:01,181 INFO: FlaskWatchdog startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:101]
2023-03-09 14:14:00,019 INFO: Checking website status at 2023-03-09 13:14:00.019119 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:213]
2023-03-09 14:14:00,036 INFO: Checking website status for inpol.mazowieckie.pl at 2023-03-09 13:14:00.036752 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:217]
2023-03-09 14:14:00,038 INFO: Requesting website status for https://inpol.mazowieckie.pl at 2023-03-09 13:14:00.038121 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:260]
2023-03-09 14:14:00,140 INFO: Status code for https://inpol.mazowieckie.pl is 200 at 2023-03-09 13:14:00.140292 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:262]
2023-03-09 14:14:00,142 INFO: Website status for inpol.mazowieckie.pl at 2023-03-09 13:14:00.142644 is True [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:219]
