2023-03-06 22:03:00,342 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106411050>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:03:00,369 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10640bd50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:06:00,014 INFO: Checking website status at 2023-03-06 21:06:00.013999 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:06:00,071 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1064033d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:06:00,186 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106189850>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:06:00,250 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1064136d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:06:00,368 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10641d990>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:06:00,444 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106152990>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:11:24,741 INFO: Checking website status at 2023-03-06 21:11:24.740650 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:11:24,793 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061ba150>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:11:24,930 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106400790>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:11:24,996 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106409ad0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:11:25,122 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10641ca90>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:11:25,144 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061997d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:12:00,013 INFO: Checking website status at 2023-03-06 21:12:00.013754 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:12:00,057 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106402390>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:12:00,155 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106409610>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:12:00,176 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10640a0d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:12:00,254 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10618a390>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:12:00,279 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10641fc50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:15:00,012 INFO: Checking website status at 2023-03-06 21:15:00.012490 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:18:00,005 INFO: Checking website status at 2023-03-06 21:18:00.005011 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:18:00,414 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1064129d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:21:00,011 INFO: Checking website status at 2023-03-06 21:21:00.011798 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:21:00,051 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10642c890>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:21:00,169 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10641cad0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:21:00,220 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1064129d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:21:00,295 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061bac90>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
