2023-03-06 21:03:00,442 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1046b0b50>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:35:48,073 INFO: Website monitoring startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:91]
2023-03-06 21:37:20,581 INFO: Website monitoring startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:91]
2023-03-06 21:37:26,996 INFO: Website monitoring startup [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:91]
2023-03-06 21:37:27,043 INFO: Checking website status at 2023-03-06 20:37:27.043848 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:39:00,008 INFO: Checking website status at 2023-03-06 20:39:00.008574 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:42:00,010 INFO: Checking website status at 2023-03-06 20:42:00.010269 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:45:00,013 INFO: Checking website status at 2023-03-06 20:45:00.013597 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:48:00,014 INFO: Checking website status at 2023-03-06 20:48:00.014108 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:51:00,010 INFO: Checking website status at 2023-03-06 20:51:00.010764 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:54:00,016 INFO: Checking website status at 2023-03-06 20:54:00.016565 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:54:00,076 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061982d0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:54:00,167 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061b8e10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:54:00,205 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106401250>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:54:00,301 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061b9250>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:54:00,322 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106198710>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:57:00,016 INFO: Checking website status at 2023-03-06 20:57:00.016853 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 21:57:00,061 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106401ad0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:57:00,158 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106409b90>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:57:00,198 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10640bdd0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:57:00,308 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10640a290>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 21:57:00,335 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10640a390>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:00:00,014 INFO: Checking website status at 2023-03-06 21:00:00.014046 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:00:00,055 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061a7e90>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:00:00,178 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106402050>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:00:00,220 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061b9210>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:00:00,320 ERROR: Request failed for website https://linktr.ee/zaorski: HTTPSConnectionPool(host='linktr.ee', port=443): Max retries exceeded with url: /zaorski (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106412090>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:00:00,342 ERROR: Request failed for website https://v3.aggr.trade/scxh: HTTPSConnectionPool(host='v3.aggr.trade', port=443): Max retries exceeded with url: /scxh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061a4b10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:03:00,013 INFO: Checking website status at 2023-03-06 21:03:00.013051 [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:151]
2023-03-06 22:03:00,067 ERROR: Request failed for website https://context.reverso.net/translation/: HTTPSConnectionPool(host='context.reverso.net', port=443): Max retries exceeded with url: /translation/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061bbdd0>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:03:00,186 ERROR: Request failed for website https://inpol.mazowieckie.pl/login: HTTPSConnectionPool(host='inpol.mazowieckie.pl', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106403750>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
2023-03-06 22:03:00,227 ERROR: Request failed for website https://github.com/wong2/chatgpt-google-extension: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /wong2/chatgpt-google-extension (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106409f10>: Failed to establish a new connection: [Errno 61] Connection refused')) [in /Users/maksimkisliak/PycharmProjects/FlaskWatchdog/app.py:162]
